
name: Build java spring app
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  JAVA_VERSION: '1.8'             # set this to the java version to use
  
jobs:
  build:
    name: Build application source
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up java ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: Build with Gradle
      run: |
        cd Application
        chmod +x gradlew
        gradle build test bootwar
    - name: Creating artifact directories
      run: |
        mkdir buildartifacts
        mkdir deploymenttemplates
    # Archive build artifact
    - name: Archive Build artifacts
      run: |
        zip -qq -r ./buildartifacts/build.zip ./Application/build
    # Uploading application to build artifact
    - name: Upload target to Build Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: buildartifacts
        path: buildartifacts

    # Archive Arm templates
    - name: Archive ArmTemplates
      run: |
        zip -qq -r ./deploymenttemplates/armtemplates.zip ./ArmTemplates
    # Uploading Arm Templates to artifacts
    - name: Upload Arm templates to Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: deploymenttemplates
        path: deploymenttemplates
